### ISSUE TITLE
Cater for installation path segment

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/prez#1]
Allow Prez to function at http://{SERVER}/path, not just http://{SERVER}

Nav links and a few other things will need pre-pending with /path

**Comment by nicholascar** [comment]
https://fastapi.tiangolo.com/advanced/behind-a-proxy/

**Comment by recalcitrantsupplant** [comment]
@jamiefeiss @nicholascar is this still relevant?

**Comment by edmondchuc** [comment]
Yes, I think so. Initially I set up GSQ Prez on a subpath at https://gsq-prez.dev.kurrawong.ai/prez, but I ended up moving it to https://api.gsq-prez.dev.kurrawong.ai because the subpath installation was not able to receive request info from the nginx proxy.

Not entirely sure if it was an issue with Prez or the proxy though.

**Comment by recalcitrantsupplant** [comment]
Catered to here: https://github.com/RDFLib/prez/blob/6d8d539075acdbd18fae8bd8162126867bdcb4ae/prez/app.py#L144
